version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
skip_commits:
  files:
    - doc/*
    - '**/*.md'
    - .vsts-ci.yml
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
  TreatWarningsAsErrors: true
  CodeAnalysisTreatWarningsAsErrors: true
before_build:
- |- # Restore TWICE. See https://github.com/AArnott/Nerdbank.GitVersioning/issues/113#issuecomment-285903085
  msbuild src\Microsoft.VisualStudio.SDK.Analyzers.sln /nologo /m /v:quiet /t:restore
  msbuild src\Microsoft.VisualStudio.SDK.Analyzers.sln /nologo /m /v:quiet /t:restore > nul
build_script:
- msbuild src\Microsoft.VisualStudio.SDK.Analyzers.sln /nologo /m /bl /v:minimal /t:build,pack
test_script:
- >-
    SET testdir=bin\Microsoft.VisualStudio.SDK.Analyzers.Tests\%configuration%\net46

    "%xunit20%\xunit.console.x86.exe"
    "%testdir%\Microsoft.VisualStudio.SDK.Analyzers.Tests.dll"
    -noshadow
    -html "%testdir%\testresults.html" -xml "%testdir%\testresults.xml"
    -appveyor
    -notrait "TestCategory=FailsInCloudTest"
    -nologo

artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
- path: msbuild.binlog
  name: Build log
- path: bin\**\testresults*
  name: Test results
