steps:

- task: CmdLine@2
  inputs:
    script: |
      del /s /q "%userprofile%\.nuget\packages"
      del /s /q "%LocalAppData%\NuGet\Cache"
      del /s /q "%AppData%\tsd-cache"
  displayName: Purge package caches
  condition: and(succeeded(), ne(variables['Hosted'], 'true'))

- task: MicroBuildSigningPlugin@1
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin
  condition: and(succeeded(), ne(variables['Hosted'], 'true'))
