trigger:
  branches:
    include: ["master", "*"]
  paths:
    exclude: [".github", "doc", "*.md"]

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: Windows
  pool: VSEng-MicroBuildVS2019
  steps:
  - template: build.yml
